name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "jiji.mascan@gmail.com"
          git config --global user.name "Jergie Mascan"

      - name: Push to gh-pages
        run: |
          git fetch --all
          git checkout gh-pages || git checkout -b gh-pages
          git merge main --allow-unrelated-histories -m "Merge main to gh-pages" --strategy-option theirs
          git push origin gh-pages
